import type { Character, Collectible, GameSettings } from './types';

const base = 'https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/models/gltf';

export const characters: Character[] = [
  {
    id: 'lala',
    name: 'Lala',
    role: 'Torbellino del festival',
    special: 'Baile del pavo real',
    description: 'Una chica que es un torbellino. Su baile "Pavo real" fue tan mítico que terminó ligando hasta con 4 chicos durante el fin de semana.',
    color: '#ef7435',
    accent: '#f6c66e',
    modelUrl: `${base}/Michelle.glb`,
    scale: 1,
  },
  {
    id: 'lety',
    name: 'Lety',
    role: 'Reina del chillout',
    special: 'Mi chillout, mis normas',
    description: 'Nos cuidó a todos, soltó su frase legendaria y racionó las golosinas para que llegaran hasta el domingo.',
    color: '#0b5964',
    accent: '#f5ead2',
    modelUrl: `${base}/kira.glb`,
    scale: 1,
  },
  {
    id: 'isa',
    name: 'Isa',
    role: 'Flechazo del sábado',
    special: 'No perdió el tiempo',
    description: 'Llegó el sábado y no perdió el tiempo: comió, bebió y ligó con el guapo del festival, un malagueño muy vacilón y gracioso.',
    color: '#2f8f83',
    accent: '#ffd166',
    modelUrl: `${base}/Michelle.glb`,
    scale: 1,
  },
  {
    id: 'patri',
    name: 'Patri',
    role: 'Intensa y graciosísima',
    special: 'Piripi power',
    description: 'Loquita por naturaleza, despistada e intensa, pero más graciosa que nadie. El viernes iba tan piripi que casi no recordaba cómo se llamaba.',
    color: '#c94f7c',
    accent: '#ffd9ec',
    modelUrl: `${base}/kira.glb`,
    scale: 1,
  },
  {
    id: 'luis',
    name: 'Luis',
    role: 'Vacile malagueño',
    special: 'Bajar el ego',
    description: 'El malagueño gracioso y vacilón cuyo gran objetivo fue bajarle el ego a Aitor con bromas usando una cinta métrica de costura y un cenicero.',
    color: '#3568a8',
    accent: '#ffc16b',
    modelUrl: `${base}/Soldier.glb`,
    scale: 1,
  },
  {
    id: 'fran',
    name: 'Fran',
    role: 'Calma con tormenta',
    special: 'Resurgir',
    description: 'Un tío tranquilo y torbellino a la vez. El sábado consiguió que Aitor resurgiera de las cenizas.',
    color: '#4f6b52',
    accent: '#d8e5b6',
    modelUrl: `${base}/readyplayer.me.glb`,
    scale: 1,
  },
  {
    id: 'clara',
    name: 'Clara',
    role: 'Dueña de la pista',
    special: 'Tomar el festival',
    description: 'Al principio parecía modosita, pero el resumen real fue claro: se hizo con el festival y no paró de bailar en todo el fin de semana.',
    color: '#8d5dd6',
    accent: '#f3dcff',
    modelUrl: `${base}/Michelle.glb`,
    scale: 1.03,
  },
  {
    id: 'jesucristo',
    name: 'Jesucristo',
    role: 'Pelazo sagrado',
    special: 'Aura del buen rollo',
    description: 'Nuestro amigo con el pelo más bonito del festival: media melena morena preciosa, majo, agradable y con una vibra impecable.',
    color: '#7c4a36',
    accent: '#ffd6b3',
    modelUrl: `${base}/readyplayer.me.glb`,
    scale: 1,
  },
  {
    id: 'aitor',
    name: 'Aitor',
    role: 'Loquito desenjaulado',
    special: 'Modo desatado',
    description: 'Un loquito desenjaulado que empieza a disfrutar de la vida junto a Patri. Quiso que todos estuvieran cómodos, relajados y felices, y se pegó una panzada a bailar fuera de lo normal.',
    color: '#d14e2f',
    accent: '#ffe0bf',
    modelUrl: `${base}/Soldier.glb`,
    scale: 1.02,
  },
];

export const collectibles: Collectible[] = [
  {
    id: 'golosinas',
    label: 'Las golosinas racionadas',
    zone: 'Chillout',
    description: 'La reserva estratégica de Lety para sobrevivir hasta el domingo sin motín.',
  },
  {
    id: 'papas_revolconas',
    label: 'Papas revolconas de la barra',
    zone: 'Barra',
    description: 'Ración caliente recogida en la barra para recuperar energía.',
  },
  {
    id: 'llave_water',
    label: 'La llave del water',
    zone: 'Water',
    description: 'Llave escondida en la zona del water estilo Moraleja.',
  },
  {
    id: 'carpeta_rosa',
    label: 'Carpeta rosa de los polvos mágicos',
    zone: 'Chillout',
    description: 'Carpeta rosa misteriosa con polvos mágicos de festival.',
  },
  {
    id: 'pistola_agua',
    label: 'Pistola de agua',
    zone: 'Playa',
    description: 'Arma refrescante para sobrevivir al calor de la isla.',
  },
  {
    id: 'tienda_sin_palos',
    label: 'Tienda de campaña sin palos',
    zone: 'Camping',
    description: 'La tienda imposible que aguanta como puede.',
  },
  {
    id: 'colchon_pinchado',
    label: 'Colchón pinchado',
    zone: 'Camping',
    description: 'Un clásico de festival: el colchón que prometía descanso y dio suelo.',
  },
  {
    id: 'barca_remo',
    label: 'Barca de remo',
    zone: 'Embarque',
    description: 'La barca para moverse por el pantano y volver a la isla.',
  },
  {
    id: 'dj_bueno',
    label: 'DJ Bueno',
    zone: 'Escenario',
    description: 'El DJ que salva la noche cuando entra el tema correcto.',
  },
  {
    id: 'dj_malo',
    label: 'DJ Malo',
    zone: 'Escenario',
    description: 'El DJ que pincha raro y provoca caos controlado.',
  },
  {
    id: 'hamaca',
    label: 'Hamaca del chillout',
    zone: 'Chillout',
    description: 'La hamaca para intentar descansar antes de volver a bailar.',
  },
  {
    id: 'fuente',
    label: 'Fuente de la isla',
    zone: 'Plaza',
    description: 'Punto de referencia con agua y luz en mitad del mapa.',
  },
  {
    id: 'pole_dance',
    label: 'Barra de pole dance',
    zone: 'Pista',
    description: 'Barra metálica para el momento más inesperado de la pista.',
  },
  {
    id: 'cinta',
    label: 'La cinta métrica',
    zone: 'Barra',
    description: 'Una de las armas del vacile con la que Luis intentó bajarle el ego a Aitor.',
  },
  {
    id: 'cenicero',
    label: 'El cenicero del malagueño',
    zone: 'Playa',
    description: 'El otro objeto clave de las bromas malagueñas del fin de semana.',
  },
  {
    id: 'pulsera',
    label: 'La pulsera cashless',
    zone: 'Taquilla',
    description: 'Todavía parece tener saldo para una última ronda en la isla.',
  },
  {
    id: 'mapa',
    label: 'El mapa del embarque',
    zone: 'Embarque',
    description: 'La ruta que llevó al grupo a la aventura más surrealista del pantano.',
  },
  {
    id: 'abanico',
    label: 'El abanico de la pista',
    zone: 'Escenario',
    description: 'El testigo silencioso de Clara y de la panzada de baile de Aitor.',
  },
  {
    id: 'melena',
    label: 'El recuerdo del pelazo',
    zone: 'Mirador',
    description: 'Una reliquia simbólica del pelo más bonito de todo el festival.',
  },
  {
    id: 'foto',
    label: 'La foto del amanecer',
    zone: 'Muralla',
    description: 'La prueba definitiva de que el grupo exprimió la isla hasta el final.',
  },
];

export const defaultSettings: GameSettings = {
  quality: 'high',
  sound: true,
  cameraShake: true,
};
